export const GET_ALL_MENTORS_IN_PROGRESS = 'GET_ALL_MENTORS_IN_PROGRESS';
export const GET_ALL_MENTORS_SUCCESS = 'GET_ALL_MENTORS_SUCCESS';
export const GET_ALL_MENTORS_FAILURE = 'GET_ALL_MENTORS_FAILURE';

export const POST_LOGIN_IN_PROGRESS = 'POST_LOGIN_IN_PROGRESS';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_BAD = 'POST_LOGIN_BAD';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';

export const GET_CURRENT_MENTOR_IN_PROGRESS = 'GET_CURRENT_MENTOR_IN_PROGRESS';
export const GET_CURRENT_MENTOR_SUCCESS = 'GET_CURRENT_MENTOR_SUCCESS';
export const GET_CURRENT_MENTOR_FAILURE = 'GET_CURRENT_MENTOR_FAILURE';

// todo
export const EDIT_BIO_IN_PROGRESS = 'EDIT_BIO_IN_PROGRESS';
export const EDIT_BIO_SUCCESS = 'EDIT_BIO_SUCCESS';
export const EDIT_BIO_FAILURE = 'EDIT_BIO_FAILURE';
