export const GET_ALL_MENTORS_IN_PROGRESS = 'GET_ALL_MENTORS_IN_PROGRESS';
export const GET_ALL_MENTORS_SUCCESS = 'GET_ALL_MENTORS_SUCCESS';
export const GET_ALL_MENTORS_FAILURE = 'GET_ALL_MENTORS_FAILURE';
