export const GET_ALL_MENTORS_IN_PROGRESS = 'GET_ALL_MENTORS_IN_PROGRESS';
export const GET_ALL_MENTORS_SUCCESS = 'GET_ALL_MENTORS_SUCCESS';
export const GET_ALL_MENTORS_FAILURE = 'GET_ALL_MENTORS_FAILURE';

export const POST_LOGIN_IN_PROGRESS = 'POST_LOGIN_IN_PROGRESS';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_BAD = 'POST_LOGIN_BAD';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';
export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';
