export const GET_ALL_MENTORS_IN_PROGRESS = 'GET_ALL_MENTORS_IN_PROGRESS';
export const GET_ALL_MENTORS_SUCCESS = 'GET_ALL_MENTORS_SUCCESS';
export const GET_ALL_MENTORS_FAILURE = 'GET_ALL_MENTORS_FAILURE';

export const SHOW_CREATE_MENTOR_MODAL = 'SHOW_CREATE_MENTOR_MODAL';
export const HIDE_CREATE_MENTOR_MODAL = 'HIDE_CREATE_MENTOR_MODAL';

export const SHOW_UPDATE_MENTOR_MODAL = 'SHOW_UPDATE_MENTOR_MODAL';
export const HIDE_UPDATE_MENTOR_MODAL = 'HIDE_UPDATE_MENTOR_MODAL';

export const SHOW_CREATE_MENTOR_DROP = 'SHOW_CREATE_MENTOR_DROP';
export const HIDE_CREATE_MENTOR_DROP = 'HIDE_CREATE_MENTOR_DROP';

export const POST_LOGIN_IN_PROGRESS = 'POST_LOGIN_IN_PROGRESS';
export const POST_LOGIN_SUCCESS = 'POST_LOGIN_SUCCESS';
export const POST_LOGIN_FAILURE = 'POST_LOGIN_FAILURE';
export const POST_LOGIN_BAD = 'POST_LOGIN_BAD';

export const HANDLE_INPUT_CHANGE = 'HANDLE_INPUT_CHANGE';

export const GET_CURRENT_MENTOR_IN_PROGRESS = 'GET_CURRENT_MENTOR_IN_PROGRESS';
export const GET_CURRENT_MENTOR_SUCCESS = 'GET_CURRENT_MENTOR_SUCCESS';
export const GET_CURRENT_MENTOR_FAILURE = 'GET_CURRENT_MENTOR_FAILURE';

export const EDIT_IN_PROGRESS = 'EDIT_IN_PROGRESS';
export const EDIT_SUCCESS = 'EDIT_SUCCESS';
export const EDIT_FAILURE = 'EDIT_FAILURE';

export const POST_FLIGHT_INFO_IN_PROGRESS = 'POST_FLIGHT_INFO_IN_PROGRESS';
export const POST_FLIGHT_INFO_SUCCESS = 'POST_FLIGHT_INFO_SUCCESS';
export const POST_FLIGHT_INFO_FAILURE = 'POST_FLIGHT_INFO_FAILURE';
export const POST_FLIGHT_INFO_BAD = 'POST_FLIGHT_INFO_BAD';

export const GET_EMAILS_IN_PROGRESS = 'GET_EMAIL_IN_PROGRESS';
export const GET_EMAILS_SUCCESS = 'GET_EMAIL_SUCCESS';
export const GET_EMAILS_FAILURE = 'GET_EMAIL_FAILURE';

export const POST_EMAIL_IN_PROGRESS = 'POST_EMAIL_IN_PROGRESS';
export const POST_EMAIL_SUCCESS = 'POST_EMAIL_SUCCESS';
export const POST_EMAIL_FAILURE = 'POST_EMAIL_FAILURE';

export const POST_FIELD_IN_PROGRESS = 'POST_FIELD_IN_PROGRESS';
export const POST_FIELD_SUCCESS = 'POST_FIELD_SUCCESS';
export const POST_FIELD_FAILURE = 'POST_FIELD_FAILURE';

export const POST_CHECK_IN_PROGRESS = 'POST_CHECK_IN_PROGRESS';
export const POST_CHECK_SUCCESS = 'POST_CHECK_SUCCESS';
export const POST_CHECK_FAILURE = 'POST_CHECK_FAILURE';

export const GET_FORM_PROGRESS = 'GET_FORM_PROGRESS';
export const GET_FORM_SUCCESS = 'GET_FORM_SUCCESS';
export const GET_FORM_FAILURE = 'GET_FORM_FAILURE';

export const POST_FORM_PROGRESS = 'POST_FORM_PROGRESS';
export const POST_FORM_SUCCESS = 'POST_FORM_SUCCESS';
export const POST_FORM_FAILURE = 'POST_FORM_FAILURE';

export const POST_PERMIT_APPROVAL_IN_PROGRESS = 'POST_PERMIT_APPROVAL_IN_PROGRESS';
export const POST_PERMIT_APPROVAL_SUCCESS = 'POST_PERMIT_APPROVAL_SUCCESS';
export const POST_PERMIT_APPROVAL_FAILURE = 'POST_PERMIT_APPROVAL_FAILURE';

export const POST_PERMISSION_APPROVAL_IN_PROGRESS = 'POST_PERMISSION_APPROVAL_IN_PROGRESS';
export const POST_PERMISSION_APPROVAL_SUCCESS = 'POST_PERMISSION_APPROVAL_SUCCESS';
export const POST_PERMISSION_APPROVAL_FAILURE = 'POST_PERMISSION_APPROVAL_FAILURE';
